FORMAT: 1A
HOST: https://api.soccersapi.com/v2.2/

# soccersapi

SoccersAPI is a RESTful service for soccer data sport. It is a PAID service with low price (started with $30 per month). Note that in order to access Soccer's API you must purchase related packages. Please contact us if you have any problem.

## Countries List [/countries/{?user,token,t}]

+ Parameters
    + user - YOUR_USER
    + token - YOUR_TOKEN
    + t - list


### List All Countries [GET] 

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Location: /countries
 
    
    + Body

 
        {
            "id": 43482,
            "name": "Afghanistan",
            "continent": "Asia",
            "sub_region": "Southern Asia",
            "code": "af"
        },
        {
            "id": 2492,
            "name": "Albania",
            "continent": "Europe",
            "sub_region": "Southern Europe",
            "code": "al"
        },
        {
            "id": 652,
            "name": "Algeria",
            "continent": "Africa",
            "sub_region": "Northern Africa",
            "code": "dz"
        }

## Country Info [/countries/{?user,token,t,id}]    

+ Parameters
    + user - YOUR_USER
    + token - YOUR_TOKEN
    + t - info
    + id - COUNTRY_ID
    
### Get country info by ID [GET]


+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Location: /countries

    + Body

   {
        "id": 43482,
        "name": "Afghanistan",
        "continent": "Asia",
        "sub_region": "Southern Asia",
        "long": "66.02528381347656",
        "lat": "33.833248138427734",
        "image": "/countries/43482.png"
    } 
 

## All Leagues [/leagues{?user,token,t}]

+ Parameters
    + user - YOUR_USER
    + token - YOUR_TOKEN
    + t - list
 

### Get a list of all leagues [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /leagues
 
    
    + Body

 
       {
            "id": 210,
            "name": "Superliga",
            "is_cup": "0",
            "id_country": 2492
        },
        {
            "id": 1397,
            "name": "League 2 Group A",
            "is_cup": "0",
            "id_country": 2492
        },
        {
            "id": 1398,
            "name": "League 2 Group b",
            "is_cup": "0",
            "id_country": 2492
        }

## League Info  [/leagues{?user,token,id,t}]

+ Parameters
    + user - YOUR_USER
    + token - YOUR_TOKEN
    + t - list
    + id - LEAGUE_ID
 

### Get League Info by ID [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /leagues
 
    
    + Body

 
       {
    "data": {
        "id": 210,
        "name": "Superliga",
        "is_cup": "0",
        "id_current_season": 16589,
        "id_current_stage": 77445682,
        "id_current_round": 165,
        "country": {
            "id": 2492,
            "name": "Albania",
            "cc": "al"
        },
        "seasons": [
            {
                "id": 8278,
                "name": "2017/2018",
                "is_current": "0"
            },
            {
                "id": 13156,
                "name": "2018/2019",
                "is_current": "0"
            },
            {
                "id": 774,
                "name": "2016/2017",
                "is_current": "0"
            },
            {
                "id": 16589,
                "name": "2019/2020",
                "is_current": "1"
            }
        ]
    }