FORMAT: 1A
HOST: https://api.soccersapi.com/v2.2/

# soccersapi

SoccersAPI is a RESTful service for soccer data sport. It is a PAID service with low price (started with $30 per month). Note that in order to access Soccer's API you must purchase related packages. Please contact us if you have any problem.

## API Versions  

       API : Soccers' API  
       API Version : v 2.2  
       API Contents : Football  

## Authentication

To authorize, use this code: 
Make sure replace YOUR TOKEN with your real token. You can generate them in your user dashboard once you hire a Soccer's API plan.
curl "ENDPOINT?user=YOURUSER&token=YOURTOKEN".

## Pagination

To reduce response time in JSON delivery, some Enpoints are paginated.
add the GET parameter page=NUMBER in the endpoint URL.
"ENDPOINT?user=YOURUSER&token=YOURTOKEN&p=PAGENUMBER".

## Match Status Explanation

| Name     | Character |
| ---      | ---       |
|  1       | The event is inplay         |
| 11       | The event is in half-time        |
| 12       | The event is in extra time          |
| 13       | The event is in penalties because extra time didn't determinate a winner         |
| 14       | Event is in break waiting for extra time or penalties          |
| 15       | Awarding of a victory to a contestant because there are no other contestants.       |
|  2       | Event will be updated later       |
|  3       | Event has ended after 90 minutes       |
| 31       | Event has ended after penalty shootout         |
| 32       | The event has finished after extra time         |
|  4       | The event has finished after extra time        |
|  5       | The event has been postponed        |
|  6       | The event has abandoned and will continue at a later time or day        |
|  7       | The event has been interrupted. Can be due to bad weather for example          |
|  8       | The event has been suspended           |
|  9       | Winner is beeing decided externally          |
| 10       | The event is delayed          |

 
## Soccer API resources

 Soccer API https://soccersapi.com  
 Docs https://soccersapi.com/page/documentation  
 Coverage  https://soccersapi.com/page/coverage  
 Support https://soccersapi.com/page/support  
 Plans & Pricing https://soccersapi.com/page/pricing  

## List Countries [/countries/{?user,token,t,page}]
 
+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - list
    + page - PAGE NUMBER
   



### TEST ENDPOINT [GET] 
 

+ Request (application/json)

+ Response 200 (application/json) 

    + Headers

            Location: /countries
 
    
    + Body

 
{
    "id": 358,
    "name": "Denmark",
    "continent": "Europe",
    "sub_region": "Northern Europe",
    "code": "dk"
},
{
    "id": 908821,
    "name": "Djibouti",
    "continent": "Africa",
    "sub_region": "Eastern Africa",
    "code": "dj"
},
{
    "id": 380193,
    "name": "Dominica",
    "continent": "Americas",
    "sub_region": "Caribbean",
    "code": "dm"
},
{
    "id": 79184,
    "name": "Dominican Republic",
    "continent": "Americas",
    "sub_region": "Caribbean",
    "code": "do"
},
{
    "id": 10203167,
    "name": "East Timor",
    "continent": "Asia",
    "sub_region": "South-Eastern Asia",
    "code": null
},
...
 

## Country Info [/countries/{?user,token,t,id}]    

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - COUNTRY ID
 
    
### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Location: /countries

    + Body

    {
        "id": 358,
        "name": "Denmark",
        "continent": "Europe",
        "sub_region": "Northern Europe",
        "long": "9.555907249450684",
        "lat": "56.10176086425781",
        "image": "/countries/358.png"
    }
 

## List Leagues [/leagues{?user,token,t,page}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - list
    + page - PAGE NUMBER
  
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /leagues
 
    
    + Body

 
 {
    "id": 1205,
    "name": "2. Division Group West",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 309,
    "name": "Superliga",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1206,
    "name": "Denmark Series Group 1",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1207,
    "name": "Denmark Series Group 2",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 315,
    "name": "Landspokal Cup",
    "is_cup": "1",
    "id_country": 358
},
{
    "id": 1201,
    "name": "2. Division Group 1",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1208,
    "name": "Denmark Series Group 3",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1202,
    "name": "2. Division Group 2",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1209,
    "name": "Denmark Series Group 4",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1203,
    "name": "2. Division Group 3",
    "is_cup": "0",
    "id_country": 358
},
{
    "id": 1204,
    "name": "2. Division Group East",
    "is_cup": "0",
    "id_country": 358
},
...

## League Info  [/leagues{?user,token,id,t}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - list
    + id - LEAGUE ID
  
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /leagues
 
    
    + Body

 
    {
        "id": 309,
        "name": "Superliga",
        "is_cup": "0",
        "id_current_season": 16058,
        "id_current_stage": 77443840,
        "id_current_round": 165,
        "country": {
            "id": 358,
            "name": "Denmark",
            "cc": "dk"
        },
        "seasons": [
            {
                "id": 6399,
                "name": "2017/2018",
                "is_current": "0"
            },
            {
                "id": 797,
                "name": "2016/2017",
                "is_current": "0"
            },
            {
                "id": 12957,
                "name": "2018/2019",
                "is_current": "0"
            },
            {
                "id": 16058,
                "name": "2019/2020",
                "is_current": "1"
            }
        ]
    }
    
## League Stats  [/stats{?user,token,id,t}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - league
    + id - LEAGUE ID
  
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /stats
 
    
    + Body

 
   {
        "season_id": 15818,
        "number_of_teams": 15,
        "number_of_matches": 210,
        "number_of_matches_played": 196,
        "number_of_goals": 581,
        "matches_both_teams_scored": 89,
        "number_of_yellowcards": 648,
        "number_of_yellowredcards": 17,
        "number_of_redcards": 14,
        "avg_goals_per_match": "2.96",
        "avg_yellowcards_per_match": "3.31",
        "avg_yellowredcards_per_match": "0.09",
        "avg_redcards_per_match": "0.07",
        "team_with_most_goals_id": 5712,
        "team_with_most_conceded_goals_id": 6534,
        "team_with_most_goals_per_match_id": 5712,
        "season_topscorer_id": 51064,
        "season_assist_topscorer_id": null,
        "team_most_cleansheets_id": 6545,
        "team_most_cleansheets_number": 16,
        "goals_scored_minutes": {
            "0-15": "11.6%",
            "15-30": "16.21%",
            "30-45": "16.38%",
            "45-60": "18.09%",
            "60-75": "18.43%",
            "75-90": "23.72%"
        },
        "goalkeeper_most_cleansheets_id": 58468,
        "goalkeeper_most_cleansheets_number": 16,
        "goal_scored_every_minutes": 25,
        "btts": "45.41",
        "goal_line": {
            "over": {
                "0_5": 90.82,
                "1_5": 76.02,
                "2_5": 56.12,
                "3_5": 39.29,
                "4_5": 18.88,
                "5_5": 9.18
            },
            "under": {
                "0_5": 9.18,
                "1_5": 23.98,
                "2_5": 43.88,
                "3_5": 60.71,
                "4_5": 81.12,
                "5_5": 90.82
            }
        }
    }
    
## League Stats by Season  [/stats{?user,token,id,t}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - season
    + id - SEASON ID
  
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /stats
 
    
    + Body

 
         {
        "season_id": 15378,
        "number_of_teams": 10,
        "number_of_matches": 62,
        "number_of_matches_played": 62,
        "number_of_goals": 146,
        "matches_both_teams_scored": 29,
        "number_of_yellowcards": 124,
        "number_of_yellowredcards": 2,
        "number_of_redcards": 12,
        "avg_goals_per_match": "2.35",
        "avg_yellowcards_per_match": "2.00",
        "avg_yellowredcards_per_match": "0.03",
        "avg_redcards_per_match": "0.19",
        "team_with_most_goals_id": 8169,
        "team_with_most_conceded_goals_id": 30231,
        "team_with_most_goals_per_match_id": 12258,
        "season_topscorer_id": null,
        "season_assist_topscorer_id": null,
        "team_most_cleansheets_id": 3659,
        "team_most_cleansheets_number": 7,
        "goals_scored_minutes": {
            "0-15": "12.33%",
            "15-30": "14.38%",
            "30-45": "13.7%",
            "45-60": "22.6%",
            "60-75": "20.55%",
            "75-90": "21.23%"
        },
        "goalkeeper_most_cleansheets_id": 221993,
        "goalkeeper_most_cleansheets_number": 7,
        "goal_scored_every_minutes": 24,
        "btts": "46.77",
        "goal_line": {
            "over": {
                "0_5": 87.1,
                "1_5": 66.13,
                "2_5": 40.32,
                "3_5": 20.97,
                "4_5": 14.52,
                "5_5": 3.23
            },
            "under": {
                "0_5": 12.9,
                "1_5": 33.87,
                "2_5": 59.68,
                "3_5": 79.03,
                "4_5": 85.48,
                "5_5": 96.77
            }
        }
    }
    
## Standings  [/leagues{?user,token,t,id_league,id_season}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - standings
    + id_league - LEAGUE ID
    + id_season - SEASON ID
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /leagues
 
    
    + Body

 
{
            "name": "Regular Season",
            "league_id": 309,
            "season_id": 16058,
            "stage_id": 77443840,
            "stage_name": "Regular Season",
            "round_id": 169549,
            "round_name": 15,
            "standings": [
                {
                    "position": 1,
                    "team_id": 977,
                    "team_name": "Midtjylland",
                    "group_id": 38,
                    "group_name": null,
                    "overall": [
                        {
                            "games_played": 15,
                            "won": 12,
                            "draw": 2,
                            "lost": 1,
                            "goal_scored": 21,
                            "goal_against": 6,
                            "goal_difference": 15,
                            "points": 38
                        }
                    ],
                    "home": [
                        {
                            "games_played": 7,
                            "won": 5,
                            "draw": 1,
                            "lost": 1,
                            "goal_scored": 8,
                            "goal_against": 4,
                            "goal_difference": 4,
                            "points": 16
                        }
                    ],
                    "away": [
                        {
                            "games_played": 8,
                            "won": 7,
                            "draw": 1,
                            "lost": 0,
                            "goal_scored": 13,
                            "goal_against": 2,
                            "goal_difference": 11,
                            "points": 22
                        }
                    ],
                    "total": {
                        "goal_difference": 15,
                        "points": 38
                    },
                    "result": "Championship Round",
                    "recent_form": "LWWWW"
                },
                {
                    "position": 2,
                    "team_id": 123,
                    "team_name": "København",
                    "group_id": 38,
                    "group_name": null,
                    "overall": [
                        {
                            "games_played": 15,
                            "won": 12,
                            "draw": 2,
                            "lost": 1,
                            "goal_scored": 21,
                            "goal_against": 6,
                            "goal_difference": 15,
                            "points": 38
                        },
                        {
                            "games_played": 15,
                            "won": 11,
                            "draw": 1,
                            "lost": 3,
                            "goal_scored": 29,
                            "goal_against": 15,
                            "goal_difference": 14,
                            "points": 34
                        }
                    ],
                    "home": [
                        {
                            "games_played": 7,
                            "won": 5,
                            "draw": 1,
                            "lost": 1,
                            "goal_scored": 8,
                            "goal_against": 4,
                            "goal_difference": 4,
                            "points": 16
                        },
                        {
                            "games_played": 7,
                            "won": 6,
                            "draw": 1,
                            "lost": 0,
                            "goal_scored": 17,
                            "goal_against": 5,
                            "goal_difference": 12,
                            "points": 19
                        }
                    ],
                    "away": [
                        {
                            "games_played": 8,
                            "won": 7,
                            "draw": 1,
                            "lost": 0,
                            "goal_scored": 13,
                            "goal_against": 2,
                            "goal_difference": 11,
                            "points": 22
                        },
                        {
                            "games_played": 8,
                            "won": 5,
                            "draw": 0,
                            "lost": 3,
                            "goal_scored": 12,
                            "goal_against": 10,
                            "goal_difference": 2,
                            "points": 15
                        }
                    ],
                    "total": {
                        "goal_difference": 14,
                        "points": 34
                    },
                    "result": "Championship Round",
                    "recent_form": "WLWWW"
                },
                {
                    "position": 3,
                    "team_id": 1827,
                    "team_name": "OB",
                    "group_id": 38,
                    "group_name": null,
                    "overall": [
                        {
                            "games_played": 15,
                            "won": 12,
                            "draw": 2,
                            "lost": 1,
                            "goal_scored": 21,
                            "goal_against": 6,
                            "goal_difference": 15,
                            "points": 38
                        },
                        {
                            "games_played": 15,
                            "won": 11,
                            "draw": 1,
                            "lost": 3,
                            "goal_scored": 29,
                            "goal_against": 15,
                            "goal_difference": 14,
                            "points": 34
                        },
                        {
                            "games_played": 15,
                            "won": 8,
                            "draw": 2,
                            "lost": 5,
                            "goal_scored": 23,
                            "goal_against": 14,
                            "goal_difference": 9,
                            "points": 26
                        }
                    ],
                    "home": [
                        {
                            "games_played": 7,
                            "won": 5,
                            "draw": 1,
                            "lost": 1,
                            "goal_scored": 8,
                            "goal_against": 4,
                            "goal_difference": 4,
                            "points": 16
                        },
                        {
                            "games_played": 7,
                            "won": 6,
                            "draw": 1,
                            "lost": 0,
                            "goal_scored": 17,
                            "goal_against": 5,
                            "goal_difference": 12,
                            "points": 19
                        },
                        {
                            "games_played": 8,
                            "won": 5,
                            "draw": 1,
                            "lost": 2,
                            "goal_scored": 16,
                            "goal_against": 8,
                            "goal_difference": 8,
                            "points": 16
                        }
                    ] 
 } ,
 ...
    
## Seasons  [/seasons{?user,token,id,t}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - SEASON ID
   
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /seasons
 
    
    + Body

 
{
        "id": 16058,
        "name": "2019/2020",
        "league_id": 309,
        "is_current": "1",
        "stages": [
            {
                "id": 77443835,
                "name": "Europa League Play-offs - Final"
            },
            {
                "id": 77443836,
                "name": "Europa League Play-offs - Semi-finals"
            },
            {
                "id": 77443837,
                "name": "Europa League Play-offs - Quarter-finals"
            },
            {
                "id": 77443838,
                "name": "Relegation Round"
            },
            {
                "id": 77443839,
                "name": "Championship Round"
            },
            {
                "id": 77443840,
                "name": "Regular Season"
            },
            {
                "id": 77444047,
                "name": "Relegation Round"
            },
            {
                "id": 77444048,
                "name": "Championship Round"
            },
            {
                "id": 77444049,
                "name": "Regular Season"
            }
        ]
    }
  
  
## Stages  [/stages{?user,token,id,t}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - STAGE ID
  
 

### TEST ENDPOINT [GET] 



+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /stages
 
    
    + Body

 
{
        "id": 77444049,
        "name": "Regular Season",
        "league_id": 309,
        "season_id": 16058,
        "is_current": "0",
        "type": null,
        "rounds": [
            {
                "id": 170547,
                "name": "1",
                "is_current": "0"
            },
            {
                "id": 170548,
                "name": "2",
                "is_current": "0"
            },
            {
                "id": 170549,
                "name": "3",
                "is_current": "0"
            },
            {
                "id": 170550,
                "name": "4",
                "is_current": "0"
            },
            {
                "id": 170551,
                "name": "5",
                "is_current": "0"
            },
            {
                "id": 170552,
                "name": "6",
                "is_current": "0"
            },
            {
                "id": 170553,
                "name": "7",
                "is_current": "0"
            },
            {
                "id": 170554,
                "name": "8",
                "is_current": "0"
            },
            {
                "id": 170555,
                "name": "9",
                "is_current": "0"
            },
            {
                "id": 170556,
                "name": "10",
                "is_current": "0"
            },
            {
                "id": 170557,
                "name": "11",
                "is_current": "0"
            },
            {
                "id": 170558,
                "name": "12",
                "is_current": "0"
            },
            {
                "id": 170559,
                "name": "13",
                "is_current": "0"
            },
            {
                "id": 170560,
                "name": "14",
                "is_current": "0"
            },
            {
                "id": 170561,
                "name": "15",
                "is_current": "0"
            },
            {
                "id": 170562,
                "name": "16",
                "is_current": "0"
            },
            {
                "id": 170563,
                "name": "17",
                "is_current": "0"
            },
            {
                "id": 170564,
                "name": "18",
                "is_current": "0"
            },
            {
                "id": 170565,
                "name": "19",
                "is_current": "0"
            },
            {
                "id": 170566,
                "name": "20",
                "is_current": "0"
            },
            {
                "id": 170567,
                "name": "21",
                "is_current": "0"
            },
            {
                "id": 170568,
                "name": "22",
                "is_current": "0"
            },
            {
                "id": 170569,
                "name": "23",
                "is_current": "0"
            },
            {
                "id": 170570,
                "name": "24",
                "is_current": "0"
            },
            {
                "id": 170571,
                "name": "25",
                "is_current": "0"
            },
            {
                "id": 170572,
                "name": "26",
                "is_current": "0"
            }
        ]
    }

## Rounds  [/rounds{?user,token,id,t}]

+ Parameters
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - ROUND ID
  
 

### TEST ENDPOINT [GET] 



+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /rounds
 
    
    + Body

 
 []
 

## Topscorers  [/topscorers{?user,token,t,id_season}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id_season - SEASON ID
     
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /topscorers
 
    
    + Body
    
    "goalscorers": [
            {
                "position": 1,
                "season_id": 12961,
                "player_id": 240598,
                "team_id": 1074,
                "stage_id": 77441746,
                "goals": 2,
                "penalty_goals": 1,
                "type": "goals"
            },
            {
                "position": 1,
                "season_id": 12961,
                "player_id": 255086,
                "team_id": 1074,
                "stage_id": 77441747,
                "goals": 2,
                "penalty_goals": 0,
                "type": "goals"
            },
            {
                "position": 1,
                "season_id": 12961,
                "player_id": 240523,
                "team_id": 6893,
                "stage_id": 7157626,
                "goals": 10,
                "penalty_goals": 4,
                "type": "goals"
            },
            
 
    "cardscorers": [
            {
                "position": 1,
                "season_id": 12961,
                "player_id": 218293,
                "team_id": 898,
                "stage_id": 77441748,
                "yellowcards": 1,
                "redcards": 0,
                "type": "cards"
            },
            {
                "position": 1,
                "season_id": 12961,
                "player_id": 2207211,
                "team_id": 1074,
                "stage_id": 77441746,
                "yellowcards": 2,
                "redcards": 0,
                "type": "cards"
            },
            {
                "position": 1,
                "season_id": 12961,
                "player_id": 215609,
                "team_id": 898,
                "stage_id": 77441747,
                "yellowcards": 1,
                "redcards": 1,
                "type": "cards"
            },
            
  
    "assistscorers": [
            {
                "position": 1,
                "season_id": 12985,
                "player_id": 25647,
                "team_id": 358,
                "stage_id": 7401010,
                "assists": 11,
                "type": "assists"
            },
            {
                "position": 2,
                "season_id": 12985,
                "player_id": 25759,
                "team_id": 957,
                "stage_id": 7401010,
                "assists": 10,
                "type": "assists"
            },
            {
                "position": 3,
                "season_id": 12985,
                "player_id": 26578,
                "team_id": 852,
                "stage_id": 7401010,
                "assists": 9,
                "type": "assists"
            },
 
...
    
    
## Team Info  [/teams{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - TEAM ID
     
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /teams
 
    
    + Body
    
    {
        "id": 977,
        "name": "Midtjylland",
        "img": "https://cdn.soccersapi.com/images/soccer/teams/150/977.png",
        "founded": "1999",
        "twitter": "",
        "current_season_id": 16058,
        "coach_id": 83012,
        "venue_id": 380,
        "country": {
            "id": 358,
            "name": "Denmark"
        }
    }
    
    
## Team Squad  [/teams{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - squad
    + id - TEAM ID
     
 
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /teams
 
    
    + Body
    
   {
            "player_id": 5665,
            "number": 31,
            "captain": 0,
            "position_id": 1,
            "injured": false,
            "minutes_played": 0,
            "appearences": 0,
            "lineups": 0,
            "substitute_in": 0,
            "substitute_out": 0,
            "substitutes_on_bench": 11,
            "goals": 0,
            "assists": 0,
            "saves": null,
            "inside_box_saves": null,
            "dispossesed": null,
            "interceptions": null,
            "yellowcards": 0,
            "yellowred": 0,
            "redcards": 0,
            "tackles": null,
            "blocks": null,
            "hit_post": null,
            "fouls": {
                "committed": null,
                "drawn": null
            },
            "crosses": {
                "total": null,
                "accurate": null
            },
            "dribbles": {
                "attempts": null,
                "success": null,
                "dribbled_past": null
            },
            "duels": {
                "total": null,
                "won": null
            },
            "passes": {
                "total": null,
                "accuracy": null,
                "key_passes": null
            },
            "penalties": {
                "won": null,
                "scores": null,
                "missed": null,
                "committed": null,
                "saves": null
            }
        },
        {
            "player_id": 82846,
            "number": 1,
            "captain": 0,
            "position_id": 1,
            "injured": false,
            "minutes_played": 1260,
            "appearences": 14,
            "lineups": 14,
            "substitute_in": 0,
            "substitute_out": 0,
            "substitutes_on_bench": 0,
            "goals": 0,
            "assists": 0,
            "saves": 34,
            "inside_box_saves": 19,
            "dispossesed": null,
            "interceptions": null,
            "yellowcards": 1,
            "yellowred": 0,
            "redcards": 0,
            "tackles": null,
            "blocks": null,
            "hit_post": null,
            "fouls": {
                "committed": 1,
                "drawn": 2
            },
            "crosses": {
                "total": null,
                "accurate": null
            },
            "dribbles": {
                "attempts": null,
                "success": null,
                "dribbled_past": null
            },
            "duels": {
                "total": 2,
                "won": 2
            },
            "passes": {
                "total": 269,
                "accuracy": 66,
                "key_passes": null
            },
            "penalties": {
                "won": null,
                "scores": null,
                "missed": null,
                "committed": null,
                "saves": 1
            }
        },
        {
            "player_id": 537148,
            "number": 30,
            "captain": 0,
            "position_id": 1,
            "injured": false,
            "minutes_played": 0,
            "appearences": 0,
            "lineups": 0,
            "substitute_in": 0,
            "substitute_out": 0,
            "substitutes_on_bench": 3,
            "goals": 0,
            "assists": 0,
            "saves": null,
            "inside_box_saves": null,
            "dispossesed": null,
            "interceptions": null,
            "yellowcards": 0,
            "yellowred": 0,
            "redcards": 0,
            "tackles": null,
            "blocks": null,
            "hit_post": null,
            "fouls": {
                "committed": null,
                "drawn": null
            },
            "crosses": {
                "total": null,
                "accurate": null
            },
            "dribbles": {
                "attempts": null,
                "success": null,
                "dribbled_past": null
            },
            "duels": {
                "total": null,
                "won": null
            },
            "passes": {
                "total": null,
                "accuracy": null,
                "key_passes": null
            },
            "penalties": {
                "won": null,
                "scores": null,
                "missed": null,
                "committed": null,
                "saves": null
            }
        },
...
    
## Team Stats  [/teams{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - stats
    + id - TEAM ID
    + id_season - SEASON ID
     
    
    

### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /teams
 
    
    + Body
    
    {
        "stage_id": 77443840,
        "win": {
            "total": 11,
            "home": 5,
            "away": 6
        },
        "draw": {
            "total": 2,
            "home": 1,
            "away": 1
        },
        "lost": {
            "total": 1,
            "home": 1,
            "away": 0
        },
        "goals_for": {
            "total": 20,
            "home": 8,
            "away": 12
        },
        "goals_against": {
            "total": 6,
            "home": 4,
            "away": 2
        },
        "clean_sheet": {
            "total": 8,
            "home": 3,
            "away": 5
        },
        "failed_to_score": {
            "total": 2,
            "home": 1,
            "away": 1
        },
        "scoring_minutes": [
            {
                "period": [
                    {
                        "minute": "0-15",
                        "count": 1,
                        "percentage": 5
                    },
                    {
                        "minute": "15-30",
                        "count": 2,
                        "percentage": 10
                    },
                    {
                        "minute": "30-45",
                        "count": 3,
                        "percentage": 15
                    },
                    {
                        "minute": "45-60",
                        "count": 4,
                        "percentage": 20
                    },
                    {
                        "minute": "60-75",
                        "count": 6,
                        "percentage": 30
                    },
                    {
                        "minute": "75-90",
                        "count": 4,
                        "percentage": 20
                    }
                ]
            }
        ],
        "avg_goals_per_game_scored": {
            "total": 1.43,
            "home": 1.14,
            "away": 1.71
        },
        "avg_goals_per_game_conceded": {
            "total": 0.43,
            "home": 0.57,
            "away": 0.29
        },
        "avg_first_goal_scored": {
            "total": "60m",
            "home": "71m",
            "away": "50m"
        },
        "avg_first_goal_conceded": {
            "total": "58m",
            "home": "73m",
            "away": "51m"
        },
        "attacks": 1679,
        "dangerous_attacks": 793,
        "avg_ball_possession_percentage": "55.50",
        "fouls": 175,
        "avg_fouls_per_game": "12.50",
        "offsides": 29,
        "redcards": 2,
        "yellowcards": 33,
        "shots_blocked": 27,
        "shots_off_target": 118,
        "avg_shots_off_target_per_game": "8.43",
        "shots_on_target": 69,
        "avg_shots_on_target_per_game": "4.93",
        "btts": 35.71,
        "goal_line": {
            "over": {
                "0_5": {
                    "home": 85.71,
                    "away": 85.71
                },
                "1_5": {
                    "home": 28.57,
                    "away": 71.43
                },
                "2_5": {
                    "home": 0,
                    "away": 14.29
                },
                "3_5": {
                    "home": 0,
                    "away": 0
                },
                "4_5": {
                    "home": 0,
                    "away": 0
                },
                "5_5": {
                    "home": 0,
                    "away": 0
                }
            },
            "under": {
                "0_5": {
                    "home": 0,
                    "away": 14.29
                },
                "1_5": {
                    "home": 57.14,
                    "away": 28.57
                },
                "2_5": {
                    "home": 71.43,
                    "away": 57.14
                },
                "3_5": {
                    "home": 100,
                    "away": 100
                },
                "4_5": {
                    "home": 100,
                    "away": 100
                },
                "5_5": {
                    "home": 100,
                    "away": 100
                }
            }
        }
    }

## Team Transfers  [/teams{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - transfers
    + id - TEAM ID
    + id_season - SEASON ID
   
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /teams
 
    
    + Body
    
    {
            "player_id": 84608,
            "from_team_id": 1690,
            "to_team_id": 977,
            "transfer": "n/a",
            "type": "IN",
            "date": "2019-07-01",
            "amount": null
        },
        {
            "player_id": 537804,
            "from_team_id": 2971,
            "to_team_id": 977,
            "transfer": "n/a",
            "type": "IN",
            "date": "2019-07-01",
            "amount": null
        },
        {
            "player_id": 537759,
            "from_team_id": 2971,
            "to_team_id": 977,
            "transfer": "n/a",
            "type": "IN",
            "date": "2019-07-01",
            "amount": null
        },
 ...
    
   
    
## Team Sidelined  [/teams{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - sidelined
    + id - TEAM ID
     
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /teams
 
    
    + Body
    
   []
   
 


## Player Info  [/players{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - PLAYER ID
    
 
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /players
 
    
    + Body
    
  {
        "id": 5665,
        "name": null,
        "common_name": "Mikkel Andersen",
        "firstname": null,
        "lastname": null,
        "birthday": null,
        "birthcountry": null,
        "birthplace": null,
        "w": null,
        "h": null,
        "img": "https://cdn.soccersapi.com/images/soccer/players/50/5665.png",
        "country": {
            "id": 38,
            "name": null,
            "cc": null
        }
    }
    
## Coach Info  [/coaches{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - COACH ID
 
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /coaches
 
    
    + Body
    
   {
        "id": 83012,
        "name": "Brian Priske Pedersen",
        "common_name": "B. Priske",
        "firstname": null,
        "lastname": null,
        "birthday": "14/05/1977",
        "birthcountry": "Denmark",
        "birthplace": "Horsens",
        "img": "https://cdn.soccersapi.com/images/soccer/coaches/50/83012.png",
        "country": {
            "id": null,
            "name": "Denmark",
            "cc": "dk"
        }
    }
    
## Venue Info  [/venues{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - VENUE ID
   
 
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /venues
 
    
    + Body
    
  {
        "id": 380,
        "name": "MCH Arena",
        "capacity": "11809",
        "city": "Herning",
        "address": "Kaj Zartows Vej 5",
        "img": "https://cdn.soccersapi.com/images/soccer/venues/380.jpg"
    }
    
## Fixtures by Date  [/fixtures{?user,token,t,d}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - schedule
    + d - YYY-MM-DD
    + p - PAGE NUMBER
   
 
    
    

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
 {
            "id": 11999895,
            "status": "0",
            "time": {
                "datetime": "2019-11-03 11:00:00",
                "date": "2019-11-03",
                "time": "11:00:00",
                "minute": "",
                "timestamp": 1572775200,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 17356,
                    "name": "UE Santa Coloma"
                },
                "away": {
                    "id": 17388,
                    "name": "Carroi"
                }
            },
            "league": {
                "id": 931,
                "name": "Primera División",
                "country_id": 2969,
                "country_name": "Andorra",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/ad.png"
            },
            "scores": {
                "home_score": "0",
                "away_score": "0",
                "ht_score": "",
                "ft_score": "",
                "et_score": ""
            },
            "venue_id": null,
            "referee_id": null,
            "round_id": 184129,
            "season_id": 16666,
            "stage_id": 77445901
        },
        {
            "id": 11999896,
            "status": "0",
            "time": {
                "datetime": "2019-11-03 13:00:00",
                "date": "2019-11-03",
                "time": "13:00:00",
                "minute": "",
                "timestamp": 1572782400,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 17339,
                    "name": "Atlètic Club d'Escaldes"
                },
                "away": {
                    "id": 17361,
                    "name": "Ordino"
                }
            },
            "league": {
                "id": 931,
                "name": "Primera División",
                "country_id": 2969,
                "country_name": "Andorra",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/ad.png"
            },
            "scores": {
                "home_score": "0",
                "away_score": "0",
                "ht_score": "",
                "ft_score": "",
                "et_score": ""
            },
            "venue_id": null,
            "referee_id": null,
            "round_id": 184129,
            "season_id": 16666,
            "stage_id": 77445901
        },
        {
            "id": 11999898,
            "status": "3",
            "time": {
                "datetime": "2019-11-03 15:00:00",
                "date": "2019-11-03",
                "time": "15:00:00",
                "minute": "90",
                "timestamp": 1572789600,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 17351,
                    "name": "Engordany"
                },
                "away": {
                    "id": 17341,
                    "name": "Inter Club d'Escaldes"
                }
            },
            "league": {
                "id": 931,
                "name": "Primera División",
                "country_id": 2969,
                "country_name": "Andorra",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/ad.png"
            },
            "scores": {
                "home_score": "1",
                "away_score": "1",
                "ht_score": "0-1",
                "ft_score": "1-1",
                "et_score": ""
            },
            "venue_id": null,
            "referee_id": null,
            "round_id": 184129,
            "season_id": 16666,
            "stage_id": 77445901
        },
...

## Fixtures Live  [/fixtures{?user,token,t}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - live
    
 
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
 {
            "id": 11950092,
            "status": 11,
            "time": {
                "datetime": "2019-11-03 18:00:00",
                "date": "2019-11-03",
                "time": "18:00:00",
                "minute": 45,
                "timestamp": false,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 12020,
                    "name": "Puma Generaleña",
                    "img": "https://cdn.soccersapi.com/images/soccer/teams/150/12020.png",
                    "form": null,
                    "coach_id": 472245
                },
                "away": {
                    "id": 15340,
                    "name": "Juventud Escazuceña",
                    "img": "https://cdn.soccersapi.com/images/soccer/teams/150/15340.png",
                    "form": null,
                    "coach_id": 37252548
                }
            },
            "league": {
                "id": 728,
                "name": "Liga de Ascenso",
                "country_id": 1777,
                "country_name": "Costa Rica",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/cr.png"
            },
            "scores": {
                "home_score": 0,
                "away_score": 0,
                "ht_score": "0-0",
                "ft_score": null,
                "et_score": null
            },
            "stadium_id": 11053,
            "referee_id": null,
            "round_id": 178353,
            "season_id": 16057,
            "stage_id": 77445312,
            "venue_id": 11053
        },
        {
            "id": 11983892,
            "status": 1,
            "time": {
                "datetime": "2019-11-03 19:00:00",
                "date": "2019-11-03",
                "time": "19:00:00",
                "minute": 90,
                "timestamp": false,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 8338,
                    "name": "Gimnasia Concepción",
                    "img": "https://cdn.soccersapi.com/images/soccer/teams/150/8338.png",
                    "form": null,
                    "coach_id": 32031251
                },
                "away": {
                    "id": 9311,
                    "name": "Sportivo Belgrano",
                    "img": "https://cdn.soccersapi.com/images/soccer/teams/150/9311.png",
                    "form": null,
                    "coach_id": 3872666
                }
            },
            "league": {
                "id": 1371,
                "name": "Torneo Federal A",
                "country_id": 82,
                "country_name": "Argentina",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/ar.png"
            },
            "scores": {
                "home_score": 2,
                "away_score": 1,
                "ht_score": "1-0",
                "ft_score": null,
                "et_score": null
            },
            "stadium_id": 5412,
            "referee_id": null,
            "round_id": 182257,
            "season_id": 16584,
            "stage_id": 77445665,
            "venue_id": 5412
        },
        {
            "id": 12000864,
            "status": 1,
            "time": {
                "datetime": "2019-11-03 19:00:00",
                "date": "2019-11-03",
                "time": "19:00:00",
                "minute": 90,
                "timestamp": false,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 5693,
                    "name": "Fénix",
                    "img": "https://cdn.soccersapi.com/images/soccer/teams/150/5693.png",
                    "form": null,
                    "coach_id": 17176692
                },
                "away": {
                    "id": 2875,
                    "name": "River Plate",
                    "img": "https://cdn.soccersapi.com/images/soccer/teams/150/2875.png",
                    "form": null,
                    "coach_id": 474365
                }
            },
            "league": {
                "id": 808,
                "name": "Primera Division",
                "country_id": 196,
                "country_name": "Uruguay",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/uy.png"
            },
            "scores": {
                "home_score": 1,
                "away_score": 0,
                "ht_score": "1-0",
                "ft_score": null,
                "et_score": null
            },
            "stadium_id": 3750,
            "referee_id": null,
            "round_id": 184254,
            "season_id": 15782,
            "stage_id": 77442532,
            "venue_id": 3750
        },
...

## Fixtures Ended  [/fixtures{?user,token,t,d}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - ended
    + d - YYYY-MM-DD
   
 
 
 
 


### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
 {
            "id": 11999898,
            "status": "3",
            "time": {
                "datetime": "2019-11-03 15:00:00",
                "date": "2019-11-03",
                "time": "15:00:00",
                "minute": "90",
                "timestamp": 1572789600,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 17351,
                    "name": "Engordany"
                },
                "away": {
                    "id": 17341,
                    "name": "Inter Club d'Escaldes"
                }
            },
            "league": {
                "id": 931,
                "name": "Primera División",
                "country_id": 2969,
                "country_name": "Andorra",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/ad.png"
            },
            "scores": {
                "home_score": "1",
                "away_score": "1",
                "ht_score": "0-1",
                "ft_score": "1-1",
                "et_score": ""
            },
            "venue_id": null,
            "referee_id": null,
            "round_id": 184129,
            "season_id": 16666,
            "stage_id": 77445901
        },
        {
            "id": 11999897,
            "status": "3",
            "time": {
                "datetime": "2019-11-03 17:00:00",
                "date": "2019-11-03",
                "time": "17:00:00",
                "minute": "90",
                "timestamp": 1572796800,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 15397,
                    "name": "Sant Julià"
                },
                "away": {
                    "id": 7096,
                    "name": "FC Santa Coloma"
                }
            },
            "league": {
                "id": 931,
                "name": "Primera División",
                "country_id": 2969,
                "country_name": "Andorra",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/ad.png"
            },
            "scores": {
                "home_score": "0",
                "away_score": "3",
                "ht_score": "0-2",
                "ft_score": "0-3",
                "et_score": ""
            },
            "venue_id": null,
            "referee_id": null,
            "round_id": 184129,
            "season_id": 16666,
            "stage_id": 77445901
        },
        {
            "id": 12007322,
            "status": "3",
            "time": {
                "datetime": "2019-11-03 11:00:00",
                "date": "2019-11-03",
                "time": "11:00:00",
                "minute": "90",
                "timestamp": 1572775200,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 4486,
                    "name": "Zira"
                },
                "away": {
                    "id": 6113,
                    "name": "Sumqayıt"
                }
            },
            "league": {
                "id": 228,
                "name": "Premier League",
                "country_id": 2491,
                "country_name": "Azerbaijan",
                "country_flag": "https://cdn.soccersapi.com/images/countries/30/az.png"
            },
            "scores": {
                "home_score": "2",
                "away_score": "2",
                "ht_score": "1-1",
                "ft_score": "2-2",
                "et_score": ""
            },
            "venue_id": null,
            "referee_id": null,
            "round_id": 185032,
            "season_id": 16562,
            "stage_id": 77445605
        },
...

## Fixtures by Stage  [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - stage
    + id - STAGE ID
     
    
 
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
 {
            "id": 11898607,
            "status": "3",
            "time": {
                "datetime": "2019-07-12 17:00:00",
                "date": "2019-07-12",
                "time": "17:00:00",
                "minute": "90",
                "timestamp": 1562943600,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 977,
                    "name": "Midtjylland"
                },
                "away": {
                    "id": 1409,
                    "name": "Esbjerg"
                }
            },
            "scores": {
                "home_score": "1",
                "away_score": "0",
                "ht_score": "0-0",
                "ft_score": "1-0",
                "et_score": ""
            },
            "round_id": 169535
        },
        {
            "id": 11898606,
            "status": "3",
            "time": {
                "datetime": "2019-07-14 10:00:00",
                "date": "2019-07-14",
                "time": "10:00:00",
                "minute": "90",
                "timestamp": 1563091200,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 428,
                    "name": "SønderjyskE"
                },
                "away": {
                    "id": 2394,
                    "name": "Randers"
                }
            },
            "scores": {
                "home_score": "2",
                "away_score": "1",
                "ht_score": "1-0",
                "ft_score": "2-1",
                "et_score": ""
            },
            "round_id": 169535
        },
        {
            "id": 11898612,
            "status": "3",
            "time": {
                "datetime": "2019-07-14 12:00:00",
                "date": "2019-07-14",
                "time": "12:00:00",
                "minute": "90",
                "timestamp": 1563098400,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 2688,
                    "name": "Lyngby"
                },
                "away": {
                    "id": 1058,
                    "name": "AaB"
                }
            },
            "scores": {
                "home_score": "2",
                "away_score": "0",
                "ht_score": "1-0",
                "ft_score": "2-0",
                "et_score": ""
            },
            "round_id": 169535
        },
...

## Fixtures by Round  [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - round
    + id - ROUND ID
    
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
{
            "id": 11898607,
            "status": "3",
            "time": {
                "datetime": "2019-07-12 17:00:00",
                "date": "2019-07-12",
                "time": "17:00:00",
                "minute": "90",
                "timestamp": 1562943600,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 977,
                    "name": "Midtjylland"
                },
                "away": {
                    "id": 1409,
                    "name": "Esbjerg"
                }
            },
            "scores": {
                "home_score": "1",
                "away_score": "0",
                "ht_score": "0-0",
                "ft_score": "1-0",
                "et_score": ""
            }
        },
        {
            "id": 11898606,
            "status": "3",
            "time": {
                "datetime": "2019-07-14 10:00:00",
                "date": "2019-07-14",
                "time": "10:00:00",
                "minute": "90",
                "timestamp": 1563091200,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 428,
                    "name": "SønderjyskE"
                },
                "away": {
                    "id": 2394,
                    "name": "Randers"
                }
            },
            "scores": {
                "home_score": "2",
                "away_score": "1",
                "ht_score": "1-0",
                "ft_score": "2-1",
                "et_score": ""
            }
        },
        {
            "id": 11898612,
            "status": "3",
            "time": {
                "datetime": "2019-07-14 12:00:00",
                "date": "2019-07-14",
                "time": "12:00:00",
                "minute": "90",
                "timestamp": 1563098400,
                "timezone": "UTC"
            },
            "teams": {
                "home": {
                    "id": 2688,
                    "name": "Lyngby"
                },
                "away": {
                    "id": 1058,
                    "name": "AaB"
                }
            },
            "scores": {
                "home_score": "2",
                "away_score": "0",
                "ht_score": "1-0",
                "ft_score": "2-0",
                "et_score": ""
            }
        },
...

## Fixture by ID  [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - event
    + id - MATCH ID
    
 
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
{
        "id": 11898612,
        "status": "3",
        "time": {
            "datetime": "2019-07-14 12:00:00",
            "date": "2019-07-14",
            "time": "12:00:00",
            "minute": "90",
            "timestamp": 1563098400,
            "timezone": "UTC"
        },
        "teams": {
            "home": {
                "id": 2688,
                "name": "Lyngby",
                "img": "https://cdn.soccersapi.com/images/soccer/teams/150/2688.png",
                "form": "3-4-3",
                "coach_id": 32002835
            },
            "away": {
                "id": 1058,
                "name": "AaB",
                "img": "https://cdn.soccersapi.com/images/soccer/teams/150/1058.png",
                "form": "4-3-3",
                "coach_id": 27440867
            }
        },
        "league": {
            "id": 309,
            "name": "Superliga",
            "country_id": 358,
            "country_name": "Denmark",
            "country_flag": "https://cdn.soccersapi.com/images/countries/30/dk.png"
        },
        "scores": {
            "home_score": "2",
            "away_score": "0",
            "ht_score": "1-0",
            "ft_score": "2-0",
            "et_score": ""
        },
        "referee_id": 44868,
        "round_id": 169535,
        "season_id": 16058,
        "stage_id": 77443840,
        "venue_id": 1614
    }

## Fixture Stats  [/stats{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match
    + id - MATCH ID
   
 
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /stats
 
    
    + Body
    
{
            "team_id": 121,
            "shots": {
                "total": 11,
                "ongoal": 5,
                "offgoal": 6,
                "blocked": 3,
                "insidebox": 9,
                "outsidebox": 2
            },
            "passes": {
                "total": 556,
                "accurate": 483,
                "percentage": 87
            },
            "attacks": {
                "attacks": 97,
                "dangerous_attacks": 52
            },
            "fouls": 8,
            "corners": 6,
            "offsides": 5,
            "possessiontime": 50,
            "yellowcards": 3,
            "redcards": 1,
            "saves": 3,
            "substitutions": 3,
            "goal_kick": 11,
            "free_kick": 21,
            "throw_in": 13
        },
        {
            "team_id": 3506,
            "shots": {
                "total": 17,
                "ongoal": 5,
                "offgoal": 10,
                "blocked": 4,
                "insidebox": 9,
                "outsidebox": 8
            },
            "passes": {
                "total": 552,
                "accurate": 504,
                "percentage": 91
            },
            "attacks": {
                "attacks": 86,
                "dangerous_attacks": 63
            },
            "fouls": 20,
            "corners": 5,
            "offsides": 2,
            "possessiontime": 50,
            "yellowcards": 5,
            "redcards": 0,
            "saves": 2,
            "substitutions": 3,
            "goal_kick": 6,
            "free_kick": 13,
            "throw_in": 9
        }
        
## Fixture Commentary  [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_comments
    + id - MATCH ID
    + order - ASC or DESC
     
 
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
 {
            "important": false,
            "order": 2,
            "goal": false,
            "minute": 1,
            "extra_minute": null,
            "comment": "Casemiro  - Real Madrid -  won a free kick in defence."
        },
        {
            "important": false,
            "order": 3,
            "goal": false,
            "minute": 1,
            "extra_minute": null,
            "comment": "Fouled by Ivan Rakitic  - Barcelona"
        },
        {
            "important": false,
            "order": 4,
            "goal": false,
            "minute": 4,
            "extra_minute": null,
            "comment": "Shot blocked. Luis Suárez  - Barcelona -  shot with right foot from the right side of the box is blocked. Assist -  Lionel Messi."
        },
...


## Fixture Events Summary [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_events
    + id - MATCH ID
    
 
 
 
 


### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
{
            "team_id": 121,
            "type": "substitution",
            "player_id": 186133,
            "player_name": "A. Paco",
            "related_player_id": 985,
            "related_player_name": "L. Suarez",
            "minute": 90,
            "extra_minute": 2,
            "reason": null,
            "injuried": null,
            "result": null
        },
        {
            "team_id": 121,
            "type": "yellowcard",
            "player_id": 30030,
            "player_name": "I. Rakitic",
            "related_player_id": null,
            "related_player_name": null,
            "minute": 85,
            "extra_minute": null,
            "reason": "Foul",
            "injuried": null,
            "result": null
        },
        {
            "team_id": 3506,
            "type": "substitution",
            "player_id": 73185,
            "player_name": "M. Kovacic",
            "related_player_id": 30327,
            "related_player_name": "T. Kroos",
            "minute": 84,
            "extra_minute": null,
            "reason": null,
            "injuried": null,
            "result": null
        },
...

## Fixture Trends [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_trends
    + id - MATCH ID
    
 
 
 
 


### TEST ENDPOINT [GET]  


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
[]

## Fixture Lineups [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_lineups
    + id - MATCH ID
    
 
 
 
 


### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
{
            "team_id": 121,
            "player_id": 31322,
            "player_name": "Marc-André ter Stegen",
            "number": 1,
            "position": "G",
            "formation_position": 1,
            "posx": null,
            "posy": null,
            "stats": {
                "shots": {
                    "shots_total": 0,
                    "shots_on_goal": 0
                },
                "goals": {
                    "scored": 0,
                    "conceded": 2
                },
                "fouls": {
                    "drawn": 0,
                    "committed": 0
                },
                "cards": {
                    "yellowcards": 0,
                    "redcards": 0
                },
                "passing": {
                    "total_crosses": 0,
                    "crosses_accuracy": 0,
                    "passes": 13,
                    "passes_accuracy": 54
                },
                "other": {
                    "assists": 0,
                    "offsides": 0,
                    "saves": 3,
                    "pen_scored": 0,
                    "pen_missed": 0,
                    "pen_saved": 0,
                    "tackles": 0,
                    "blocks": 0,
                    "interceptions": 0,
                    "clearances": 0,
                    "minutes_played": 90
                }
            }
        },
        {
            "team_id": 121,
            "player_id": 186077,
            "player_name": "Sergi Roberto",
            "number": 20,
            "position": "D",
            "formation_position": 2,
            "posx": null,
            "posy": null,
            "stats": {
                "shots": {
                    "shots_total": 0,
                    "shots_on_goal": 0
                },
                "goals": {
                    "scored": 0,
                    "conceded": 0
                },
                "fouls": {
                    "drawn": 0,
                    "committed": 1
                },
                "cards": {
                    "yellowcards": 0,
                    "redcards": 1
                },
                "passing": {
                    "total_crosses": 1,
                    "crosses_accuracy": 1,
                    "passes": 34,
                    "passes_accuracy": 94
                },
                "other": {
                    "assists": 1,
                    "offsides": 0,
                    "saves": 0,
                    "pen_scored": 0,
                    "pen_missed": 0,
                    "pen_saved": 0,
                    "tackles": 0,
                    "blocks": 0,
                    "interceptions": 0,
                    "clearances": 0,
                    "minutes_played": 90
                }
            }
        },
        {
            "team_id": 121,
            "player_id": 3817,
            "player_name": "Gerard Piqué",
            "number": 3,
            "position": "D",
            "formation_position": 3,
            "posx": null,
            "posy": null,
            "stats": {
                "shots": {
                    "shots_total": 1,
                    "shots_on_goal": 0
                },
                "goals": {
                    "scored": 0,
                    "conceded": 0
                },
                "fouls": {
                    "drawn": 1,
                    "committed": 0
                },
                "cards": {
                    "yellowcards": 0,
                    "redcards": 0
                },
                "passing": {
                    "total_crosses": 0,
                    "crosses_accuracy": 0,
                    "passes": 36,
                    "passes_accuracy": 83
                },
                "other": {
                    "assists": 0,
                    "offsides": 0,
                    "saves": 0,
                    "pen_scored": 0,
                    "pen_missed": 0,
                    "pen_saved": 0,
                    "tackles": 4,
                    "blocks": 1,
                    "interceptions": 0,
                    "clearances": 5,
                    "minutes_played": 90
                }
            }
        },
...

## Fixture Bench [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_bench
    + id - MATCH ID
   
 
 
 
 


### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
{
            "team_id": 121,
            "player_id": 23780,
            "player_name": "Jasper Cillessen",
            "number": 13,
            "position": "G",
            "formation_position": null,
            "posx": null,
            "posy": null,
            "stats": {
                "shots": {
                    "shots_total": null,
                    "shots_on_goal": null
                },
                "goals": {
                    "scored": null,
                    "conceded": null
                },
                "fouls": {
                    "drawn": null,
                    "committed": null
                },
                "cards": {
                    "yellowcards": null,
                    "redcards": null
                },
                "passing": {
                    "total_crosses": null,
                    "crosses_accuracy": null,
                    "passes": null,
                    "passes_accuracy": null
                },
                "other": {
                    "assists": null,
                    "offsides": null,
                    "saves": null,
                    "pen_scored": null,
                    "pen_missed": null,
                    "pen_saved": null,
                    "tackles": null,
                    "blocks": null,
                    "interceptions": null,
                    "clearances": null,
                    "minutes_played": null
                }
            }
        },
        {
            "team_id": 121,
            "player_id": 596,
            "player_name": "Thomas Vermaelen",
            "number": 25,
            "position": "D",
            "formation_position": null,
            "posx": null,
            "posy": null,
            "stats": {
                "shots": {
                    "shots_total": null,
                    "shots_on_goal": null
                },
                "goals": {
                    "scored": null,
                    "conceded": null
                },
                "fouls": {
                    "drawn": null,
                    "committed": null
                },
                "cards": {
                    "yellowcards": null,
                    "redcards": null
                },
                "passing": {
                    "total_crosses": null,
                    "crosses_accuracy": null,
                    "passes": null,
                    "passes_accuracy": null
                },
                "other": {
                    "assists": null,
                    "offsides": null,
                    "saves": null,
                    "pen_scored": null,
                    "pen_missed": null,
                    "pen_saved": null,
                    "tackles": null,
                    "blocks": null,
                    "interceptions": null,
                    "clearances": null,
                    "minutes_played": null
                }
            }
        },
        {
            "team_id": 121,
            "player_id": 160148,
            "player_name": "Nélson Semedo",
            "number": 2,
            "position": "D",
            "formation_position": null,
            "posx": null,
            "posy": null,
            "stats": {
                "shots": {
                    "shots_total": 0,
                    "shots_on_goal": 0
                },
                "goals": {
                    "scored": 0,
                    "conceded": 0
                },
                "fouls": {
                    "drawn": 1,
                    "committed": 0
                },
                "cards": {
                    "yellowcards": 0,
                    "redcards": 0
                },
                "passing": {
                    "total_crosses": 0,
                    "crosses_accuracy": 0,
                    "passes": 17,
                    "passes_accuracy": 89
                },
                "other": {
                    "assists": 0,
                    "offsides": 0,
                    "saves": 0,
                    "pen_scored": 0,
                    "pen_missed": 0,
                    "pen_saved": 0,
                    "tackles": 0,
                    "blocks": 0,
                    "interceptions": 1,
                    "clearances": 1,
                    "minutes_played": 44
                }
            }
        },
...


## Fixture Sidelined [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_sidelined
    + id - MATCH ID
   
 
 
 
 


### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
 []
 
## Fixture Odds [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_odds
    + id - MATCH ID
   
 
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
  {
            "id": 39,
            "name": "3Way Result",
            "bookmakers": {
                "data": [
                    {
                        "id": 2,
                        "name": "bet365",
                        "odds": {
                            "data": [
                                {
                                    "label": "1",
                                    "value": 3.5,
                                    "probability": "28.57%",
                                    "dp3": "3.50",
                                    "american": 250,
                                    "factional": null,
                                    "winning": true,
                                    "handicap": null,
                                    "total": null,
                                    "bookmaker_event_id": null,
                                    "last_update": {
                                        "date": "2019-07-14 11:21:50.000000",
                                        "timezone_type": 3,
                                        "timezone": "UTC"
                                    }
                                },
                                {
                                    "label": "X",
                                    "value": 3.5,
                                    "probability": "28.57%",
                                    "dp3": "3.50",
                                    "american": 250,
                                    "factional": null,
                                    "winning": false,
                                    "handicap": null,
                                    "total": null,
                                    "bookmaker_event_id": null,
                                    "last_update": {
                                        "date": "2019-07-14 11:21:50.000000",
                                        "timezone_type": 3,
                                        "timezone": "UTC"
                                    }
                                },
                                {
                                    "label": "2",
                                    "value": 2,
                                    "probability": "50%",
                                    "dp3": "20",
                                    "american": 100,
                                    "factional": null,
                                    "winning": false,
                                    "handicap": null,
                                    "total": null,
                                    "bookmaker_event_id": null,
                                    "last_update": {
                                        "date": "2019-07-14 11:21:50.000000",
                                        "timezone_type": 3,
                                        "timezone": "UTC"
                                    }
                                }
                            ]
                        }
                    },
                    
## Fixture Inplay Odds [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_oddsinplay
    + id - MATCH ID
   
 
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
  {
            "id": 39,
            "name": "3Way Result",
            "bookmakers": {
                "data": [
                    {
                        "id": 2,
                        "name": "bet365",
                        "odds": {
                            "data": [
                                {
                                    "label": "Corinthians",
                                    "info": "Corinthians",
                                    "value": "1.01",
                                    "american": -10000,
                                    "fractional": "1/100",
                                    "suspend": false,
                                    "description": "",
                                    "handicap": "",
                                    "last_update": {
                                        "date": "2019-11-07 00:27:49.000000",
                                        "timezone_type": 3,
                                        "timezone": "UTC"
                                    }
                                },
                                {
                                    "label": "Draw",
                                    "info": "Draw",
                                    "value": "26.00",
                                    "american": 2500,
                                    "fractional": "25/1",
                                    "suspend": false,
                                    "description": "",
                                    "handicap": "",
                                    "last_update": {
                                        "date": "2019-11-07 00:27:49.000000",
                                        "timezone_type": 3,
                                        "timezone": "UTC"
                                    }
                                },
                                {
                                    "label": "Fortaleza",
                                    "info": "Fortaleza",
                                    "value": "501.00",
                                    "american": 50000,
                                    "fractional": "500/1",
                                    "suspend": false,
                                    "description": "",
                                    "handicap": "",
                                    "last_update": {
                                        "date": "2019-11-07 00:27:49.000000",
                                        "timezone_type": 3,
                                        "timezone": "UTC"
                                    }
                                }
                    ]

## Fixture TV  [/fixtures{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - match_tvs
    + id - MATCH ID
   
 
 

### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /fixtures
 
    
    + Body
    
  []
 
## Referees Info [/referees{?user,token,t,id}]

+ Parameters
    
    + user - YOUR USER
    + token - YOUR TOKEN
    + t - info
    + id - REFEREE ID
 
 
 
 


### TEST ENDPOINT [GET] 


+ Request (application/json)

+ Response 200 (application/json)
 


    + Headers

            Location: /referees
 
    
    + Body
    
 
    {
        "id": 33775,
        "name": "Pierre Atcho",
        "common_name": "P. Atcho",
        "firstname": "Pierre",
        "lastname": "Atcho"
    }